<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SqlErrorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SqlErrorRepository extends EntityRepository
{
    public function getSqlError($id = 1)
    {
        $sql_error = $this->findOneBy(
            array('id' => $id)
        );

        dump($sql_error);

        return $sql_error;
    }

}
