<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * XSSAttackRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class XSSAttackRepository extends EntityRepository
{

}
