<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * XSSAttackRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class XSSAttackRepository extends EntityRepository
{
    public function findAll()
    {
        return $this->getEntityManager()
        ->createQuery(
            'SELECT x FROM AppBundle:XSSAttack x'
        )
        ->getResult();
    }
}
