#app:
#    resource: "@AppBundle/Controller/"
#    type:     annotation
rest_api:
    type:     rest
    prefix:   /api
    resource: "@AppBundle/Resources/config/api-routing.yml"
index:
    type: annotation
    resource: "@AppBundle/Controller/DefaultController.php"

#fos_user:
#    resource: "@FOSUserBundle/Resources/config/routing/all.xml"