# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
<<<<<<< HEAD

    guzzle.client:
          class: Guzzle\Service\Client
=======
    app.pentester.sql:
        class: AppBundle\Utils\Pentester\SqlPentester
        arguments: ["@guzzle.client"]
    guzzle.client:
        class: %guzzle.client.class%
    guzzle.plugin.cookie:
        class: %guzzle.plugin.cookie.class%
        calls:
            - [addSubscriber, ['@guzzle.client']]
>>>>>>> refs/remotes/origin/enhancement/interfaces_architecture
