# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.pentester.sql:
        class: AppBundle\Utils\Pentester\SqlPentester
        arguments: ["@guzzle.client", "@doctrine.orm.entity_manager"]
    app.pentester.fuzz:
        class: AppBundle\Utils\Pentester\FuzzPentester
        arguments: ["@guzzle.client", "@doctrine.orm.entity_manager", "@app.bruteforcer.easypasswords"]
    app.bruteforcer.easypasswords:
        class: AppBundle\Utils\Bruteforcer\EasyCredentials
    guzzle.client:
        class: %guzzle.client.class%
    guzzle.plugin.cookie:
        class: %guzzle.plugin.cookie.class%
        calls:
            - [addSubscriber, ['@guzzle.client']]

#    wsse.security.authentication.provider:
#        class: AppBundle\Security\Authentication\Provider\WsseProvider
#        arguments:
#            - 'fos_user.user_provider.username'
#            - '%kernel.cache_dir%/security/nonces'
#        public: false
#
#    wsse.security.authentication.listener:
#        class: AppBundle\Security\Firewall\WsseListener
#        arguments: ['@security.token_storage', '@security.authentication.manager']
#        public: false

#    app.authentification_listener:
#        class: AppBundle\EventListener\AuthentificationListener
#        arguments:
#            entityManager: "@doctrine.orm.entity_manager"
#        tags:
#            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
#    app.authentification_exception_listener:
#        class: AppBundle\EventListener\ApiAuthentificationFailureExceptionListener
#        tags:
#            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }